apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: observability-certificate
  namespace: cert-manager
spec:
  # The secret name where cert-manager
  # should store the signed certificate.
  secretName: observability-certificate
  dnsNames:
    - monitoring.tulski.com
  # Duration of the certificate.
  duration: 168h
  # Renew a day before the certificate expiration.
  renewBefore: 24h
  # Reference the Origin CA Issuer you created above,
  # which must be in the same namespace.
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer