apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-config
  namespace: cert-manager
type: Opaque
data:
  api-token: <api_token>

---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: cert-manager
spec:
  acme:
    email: michaltul2@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
      - dns01:
          cloudflare:
            email: michaltul2@gmail.com
            apiTokenSecretRef:
              name: cloudflare-config
              key: api-token